### ISSUE TITLE
chore: Criar definição de arquivos para formatação automática de código

### ISSUE THREAD

**Issue by samuelsilvadev** [taok-monitor/taok-front#13]
Descrição da ideia de forma simples 

## Objetivo
Qual o objetivo da ideia o que ela entrega de valor

- Conseguirmos manter o mesmo styleguide de formatação de código entre os devs que contribuirem com o projecto.

### Arquivos sugeridos

- eslint
- editorconfig
- prettier

**Comment by cassunde** [comment]
Ok, sem dúvida essencial
