### ISSUE TITLE
breaking page when using mobile browser

### ISSUE THREAD

**Issue by cassunde** [taok-monitor/taok-front#18]
**Expected Behavior**
End date field should have size equal the start date filed 

**Current Behavior**
end date field is greater that start date field, breaking the page when using mobile browser

**Comment by samuelsilvadev** [comment]
I can take this one

**Comment by samuelsilvadev** [comment]
@taok-monitor/team I'd tested on mobile devices, and using a smaller one (iphone 5s - 320px) I came up with the following result, what do u think guys?

![image](https://user-images.githubusercontent.com/13966565/61580034-1363bb00-ab05-11e9-9770-2410c8566dde.png)

**Comment by samuelsilvadev** [comment]
@cassunde  is the main problem this one?

![image](https://user-images.githubusercontent.com/13966565/61580191-0051ea80-ab07-11e9-9eb8-406c7adaaa28.png)

**Comment by samuelsilvadev** [comment]
my ideia was to do something like this to solve it

- give to the input `width: 100%` until it reaches the medium device

![image](https://user-images.githubusercontent.com/13966565/61580323-94708180-ab08-11e9-9be8-54831d0f1fe1.png)

**Comment by cassunde** [comment]
you know some component that show calendar to user choose a date in modal, equals android component

**Comment by cassunde** [comment]
Ok, Send this correction

**Comment by samuelsilvadev** [comment]
> you know some component that show calendar to user choose a date in modal, equals android component

not really, but I can look for some
